2023-12-08 23:01:30: Experiment log path in: C:\Users\30697\Desktop\UrbanComputingFinalProject\UrbanComputingFinalProject\ST-SSL\experiments\NYCBike1\20231208-230130
2023-12-08 23:01:30: Experiment configs are: Namespace(batch_size=32, best_path='None', d_input=2, d_model=64, d_output=2, data_dir='data', dataset='NYCBike1', debug=False, device='cpu', dropout=0.2, early_stop=True, early_stop_patience=15, epochs=100, grad_norm=True, graph_file='data/NYCBike1/adj_mx.npz', input_length=19, log_dir='C:\\Users\\30697\\Desktop\\UrbanComputingFinalProject\\UrbanComputingFinalProject\\ST-SSL\\experiments\\NYCBike1\\20231208-230130', lr_init=0.001, max_grad_norm=5, mode='train', nmb_prototype=6, num_nodes=128, percent=0.1, seed=31, shm_temp=0.5, temp=4, test_batch_size=32, use_dwa=True, yita=0.6)
2023-12-08 23:01:30: Traceback (most recent call last):
  File "C:\Users\30697\anaconda3\envs\ST-SLL\lib\site-packages\networkx\convert_matrix.py", line 1107, in from_numpy_array
    python_type = kind_to_python_type[dt.kind]
AttributeError: 'torch.dtype' object has no attribute 'kind'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "c:/Users/30697/Desktop/UrbanComputingFinalProject/UrbanComputingFinalProject/ST-SSL/main.py", line 59, in model_supervisor
    results = trainer.train() # best_eval_loss, best_epoch
  File "c:\Users\30697\Desktop\UrbanComputingFinalProject\UrbanComputingFinalProject\ST-SSL\model\trainer.py", line 109, in train
    train_epoch_loss, loss_t = self.train_epoch(epoch, loss_weights)
  File "c:\Users\30697\Desktop\UrbanComputingFinalProject\UrbanComputingFinalProject\ST-SSL\model\trainer.py", line 57, in train_epoch
    repr1, repr2 = self.model(data, self.graph) # nvc
  File "C:\Users\30697\anaconda3\envs\ST-SLL\lib\site-packages\torch\nn\modules\module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "c:\Users\30697\Desktop\UrbanComputingFinalProject\UrbanComputingFinalProject\ST-SSL\model\models.py", line 35, in forward
    graph2 = aug_topology(s_sim_mx, graph, percent=self.args.percent*2)
  File "c:\Users\30697\Desktop\UrbanComputingFinalProject\UrbanComputingFinalProject\ST-SSL\model\aug.py", line 88, in aug_topology
    p = sparsity_test(input_graph)
  File "c:\Users\30697\Desktop\UrbanComputingFinalProject\UrbanComputingFinalProject\ST-SSL\model\aug.py", line 37, in sparsity_test
    G = nx.from_numpy_array(adj_matrix)
  File "C:\Users\30697\anaconda3\envs\ST-SLL\lib\site-packages\networkx\convert_matrix.py", line 1109, in from_numpy_array
    raise TypeError(f"Unknown numpy data type: {dt}") from err
TypeError: Unknown numpy data type: torch.float32

